# syntax=docker/dockerfile:1

FROM python:3.10-slim-bookworm

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main_monitor.py .
COPY db_utils.py .


# Create the non-root user
RUN useradd -m appuser

# Change ownership of the app directory to the new user
RUN chown -R appuser:appuser /app

# Now, switch to the non-root user
USER appuser

ENTRYPOINT ["python", "main_monitor.py"]