# syntax=docker/dockerfile:1

FROM python:3.10-slim-bookworm

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main_monitor.py .
COPY db_utils.py .


RUN useradd -m appuser
USER appuser

ENTRYPOINT ["python", "main_monitor.py"]